package com.elitise.appv2;

import android.content.Context;
import android.graphics.Paint;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffXfermode;
import android.graphics.Matrix;
import android.graphics.PointF;
import android.graphics.RectF;
import android.graphics.Shader;
import android.graphics.LinearGradient;
import android.graphics.RadialGradient;
import android.graphics.BlurMaskFilter;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Path;
import android.graphics.DashPathEffect;
import android.graphics.SweepGradient;
import android.text.Layout;
import android.text.StaticLayout;
import android.text.TextPaint;
import android.graphics.Typeface;
import java.util.Stack;



/**
 * Created by ShannonGreen on 1/18/17.
 * Copyright © 2017 InduraPower. All rights reserved.
 *
 * Generated by PaintCode
 * http://www.paintcodeapp.com
 *
 * @author ShannonGreen
 */
public class TempGauge {
    // Context Property Declaration

    public static Context context = null;

    // Resizing Behavior

    public enum ResizingBehavior {
        AspectFit, //!< The content is proportionally resized to fit into the target rectangle.
        AspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
        Stretch, //!< The content is stretched to match the entire target rectangle.
        Center, //!< The content is centered in the target rectangle, but it is NOT resized.
    }

    // Canvas Drawings

    // Temp

    public static void drawTempGauge(Canvas canvas, int gradColor1, int gradColor2, int gradColor3, int gradColor4, String valueText, float minValue, float maxValue, float value, String tick0Label, String tick1Label, String tick2Label, String tick3Label, String tick4Label, String tick5Label, String tick6Label, String tick7Label, String tick8Label, String tick9Label, String tick10Label, String tick11Label, float redRangeWidth) {
        TempGauge.drawTempGauge(canvas, new RectF(0f, 0f, 217f, 174f), ResizingBehavior.AspectFit, gradColor1, gradColor2, gradColor3, gradColor4, valueText, minValue, maxValue, value, tick0Label, tick1Label, tick2Label, tick3Label, tick4Label, tick5Label, tick6Label, tick7Label, tick8Label, tick9Label, tick10Label, tick11Label, redRangeWidth);
    }

    public static void drawTempGauge(Canvas canvas, RectF targetFrame, ResizingBehavior resizing, int gradColor1, int gradColor2, int gradColor3, int gradColor4, String valueText, float minValue, float maxValue, float value, String tick0Label, String tick1Label, String tick2Label, String tick3Label, String tick4Label, String tick5Label, String tick6Label, String tick7Label, String tick8Label, String tick9Label, String tick10Label, String tick11Label, float redRangeWidth) {
        // General Declarations
        Stack<Matrix> currentTransformation = new Stack<Matrix>();
        currentTransformation.push(new Matrix());
        Paint paint;

        // Local Colors
        int shadow4Color = Color.argb(255, 255, 194, 180);
        int textColor = Color.argb(255, 224, 70, 34);
        int yellow = Color.argb(255, 255, 255, 0);

        // Local Gradients
        PaintCodeGradient dialGradient = new PaintCodeGradient(new int[]{gradColor1, PaintCodeColor.colorByBlendingColors(gradColor1, 0.5f, gradColor2), gradColor2, PaintCodeColor.colorByBlendingColors(gradColor2, 0.5f, gradColor3), gradColor3, PaintCodeColor.colorByBlendingColors(gradColor3, 0.5f, gradColor4), gradColor4}, new float[]{0.07f, 0.25f, 0.44f, 0.56f, 0.65f, 0.85f, 1f});
        PaintCodeGradient gradient2 = new PaintCodeGradient(new int[]{Color.GRAY, PaintCodeColor.colorByBlendingColors(Color.GRAY, 0.5f, Color.WHITE), Color.WHITE}, new float[]{0.24f, 0.33f, 1f});

        // Local Shadows
        PaintCodeShadow shadow4 = new PaintCodeShadow(shadow4Color, 0f, 0f, 8f);
        PaintCodeShadow shadow2 = new PaintCodeShadow(Color.BLACK, 1f, -1f, 1f);
        PaintCodeShadow shadow = new PaintCodeShadow(Color.DKGRAY, -3f, 3f, 7f);

        // Local Variables
        float angleOffset = ((maxValue - minValue) / 2f + minValue) * 254f / (float) (maxValue - minValue);
        float needleAngle = -(value * 254f / (float) (maxValue - minValue)) + angleOffset;

        // Resize to Target Frame
        canvas.save();
        currentTransformation.push(new Matrix(currentTransformation.peek()));
        RectF resizedFrame = TempGauge.resizingBehaviorApply(resizing, new RectF(0f, 0f, 217f, 174f), targetFrame);
        canvas.translate(new PointF(resizedFrame.left, resizedFrame.top).x, new PointF(resizedFrame.left, resizedFrame.top).y);
        canvas.scale(resizedFrame.width() / 217f, resizedFrame.height() / 174f);

        // Group
        {
            // Bezier 2
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(2f, 2f);
            currentTransformation.peek().postTranslate(2f, 2f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF bezier2Rect = new RectF(0f, 0f, 85f, 72f);
            Path bezier2Path = new Path();
            bezier2Path.moveTo(75.06f, 15.54f);
            bezier2Path.cubicTo(88.32f, 31.71f, 88.32f, 55.29f, 75.06f, 71.46f);
            bezier2Path.cubicTo(75f, 71.79f, 75f, 72f, 75f, 72f);
            bezier2Path.lineTo(10f, 72f);
            bezier2Path.cubicTo(10f, 72f, 10f, 71.79f, 10f, 71.41f);
            bezier2Path.cubicTo(9.2f, 70.55f, 8.49f, 69.62f, 7.83f, 68.66f);
            bezier2Path.cubicTo(-4.87f, 50.37f, -1.91f, 24.86f, 15.18f, 10.18f);
            bezier2Path.cubicTo(20.5f, 5.61f, 26.58f, 2.61f, 32.91f, 1.11f);
            bezier2Path.cubicTo(47.99f, -2.45f, 64.43f, 2.58f, 75.06f, 15.54f);
            bezier2Path.close();

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(Color.WHITE);
            canvas.drawPath(bezier2Path, paint);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(1.5f);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.BLACK);
            canvas.drawPath(bezier2Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Bezier
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(106.78f, 86.83f);
            currentTransformation.peek().postTranslate(106.78f, 86.83f);
            canvas.rotate(0.15f);
            currentTransformation.peek().postRotate(0.15f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF bezierRect = new RectF(-40.25f, -34.25f, 41.25f, 34.24f);
            Path bezierPath = new Path();
            bezierPath.moveTo(31.72f, -19.47f);
            bezierPath.cubicTo(44.43f, -4.08f, 44.43f, 18.35f, 31.72f, 33.73f);
            bezierPath.cubicTo(31.66f, 34.05f, 31.66f, 34.24f, 31.66f, 34.24f);
            bezierPath.lineTo(-30.66f, 34.24f);
            bezierPath.cubicTo(-30.66f, 34.24f, -30.66f, 34.05f, -30.66f, 33.69f);
            bezierPath.cubicTo(-31.43f, 32.87f, -32.11f, 31.98f, -32.74f, 31.07f);
            bezierPath.cubicTo(-44.92f, 13.67f, -42.08f, -10.61f, -25.69f, -24.57f);
            bezierPath.cubicTo(-20.6f, -28.91f, -14.76f, -31.77f, -8.69f, -33.19f);
            bezierPath.cubicTo(5.76f, -36.58f, 21.53f, -31.8f, 31.72f, -19.47f);
            bezierPath.close();

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(Color.BLACK);
            canvas.drawPath(bezierPath, paint);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(0.5f);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.BLACK);
            canvas.drawPath(bezierPath, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(46f, 40f);
            currentTransformation.peek().postTranslate(46f, 40f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF ovalRect = new RectF(0f, 0f, 50.91f, 53.05f);
            Path ovalPath = new Path();
            ovalPath.addArc(ovalRect, -217f, 256f);
            ovalPath.lineTo(ovalRect.centerX(), ovalRect.centerY());
            ovalPath.close();

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setShader(dialGradient.linearGradient(-0f, 21.61f, 50.91f, 21.61f));
//            int [] colors2 = {Color.BLUE,Color.GREEN,Color.YELLOW,Color.parseColor("#FFA500"),Color.RED};
//            float [] postion2 = {0f,0.2f,0.6f,0.8f,1f};
//            paint.setShader(new SweepGradient(canvas.getWidth()/2.0f,canvas.getHeight()/2.0f,colors2,postion2));.
            canvas.drawPath(ovalPath, paint);
            currentTransformation.pop();
            canvas.restore();

            // Oval 4
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(18.22f, 14.96f);
            currentTransformation.peek().postTranslate(18.22f, 14.96f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF oval4Rect = new RectF(0f, 0f, 73f, 72f);
            Path oval4Path = new Path();
            oval4Path.addArc(oval4Rect, -220f, 260f);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(1f);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.WHITE);
            canvas.drawPath(oval4Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval 5
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(109.28f, 99.78f);
            currentTransformation.peek().postTranslate(109.28f, 99.78f);
            canvas.rotate(0.7f);
            currentTransformation.peek().postRotate(0.7f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF oval5Rect = new RectF(-38f, -37.5f, 38f, 37.5f);
            Path oval5Path = new Path();
            oval5Path.addArc(oval5Rect, -220f, 260f);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(2f);
            paint.setStrokeMiter(10f);
            paint.setPathEffect(new DashPathEffect(new float[]{0.5f, 1f}, 0f));
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.RED);
            canvas.drawPath(oval5Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval 6
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(109.28f, 100.96f);
            currentTransformation.peek().postTranslate(109.28f, 100.96f);
            canvas.rotate(2.41f);
            currentTransformation.peek().postRotate(2.41f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF oval6Rect = new RectF(-35f, -35f, 35f, 35f);
            Path oval6Path = new Path();
            oval6Path.addArc(oval6Rect, -220f, 260f);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(2f);
            paint.setStrokeMiter(10f);
            paint.setPathEffect(new DashPathEffect(new float[]{0.5f, 6.55f}, 0f));
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.WHITE);
            canvas.drawPath(oval6Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval 7
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(106.14f, 103.75f);
            currentTransformation.peek().postTranslate(106.14f, 103.75f);
            canvas.rotate(-1.67f);
            currentTransformation.peek().postRotate(-1.67f);
            RectF oval7Rect = new RectF(-53.23f, -56.82f, 53.23f, 56.82f);
            Path oval7Path = new Path();
            oval7Path.addArc(oval7Rect, -15f, 51f);



            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(redRangeWidth);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.RED);
            if(redRangeWidth != 0) {
                canvas.drawPath(oval7Path, paint);
            }
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 12
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(154.05f, 139.1f);
            currentTransformation.peek().postTranslate(154.05f, 139.1f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text12Rect = new RectF(0f, 0f, 12.42f, 6.18f);
            TextPaint text12TextPaint = new TextPaint();
            text12TextPaint.setColor(yellow);
            text12TextPaint.setAntiAlias(true);
            text12TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text12TextPaint.setTextSize(4f);
            StaticLayout text12StaticLayout = new StaticLayout(tick11Label, text12TextPaint, (int) text12Rect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text12Rect);
            canvas.translate(text12Rect.left, text12Rect.top + (text12Rect.height() - text12StaticLayout.getHeight()) / 2f);
            text12StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 2
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(21.78f, 85.09f);
            currentTransformation.peek().postTranslate(21.78f, 85.09f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text2Rect = new RectF(0f, 0f, 14.13f, 6.18f);
            TextPaint text2TextPaint = new TextPaint();
            text2TextPaint.setColor(yellow);
            text2TextPaint.setAntiAlias(true);
            text2TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text2TextPaint.setTextSize(4f);
            StaticLayout text2StaticLayout = new StaticLayout(tick2Label, text2TextPaint, (int) text2Rect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text2Rect);
            canvas.translate(text2Rect.left, text2Rect.top + (text2Rect.height() - text2StaticLayout.getHeight()) / 2f);
            text2StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 3
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(22.39f, 109.68f);
            currentTransformation.peek().postTranslate(22.39f, 109.68f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text3Rect = new RectF(0f, 0f, 13.89f, 6.18f);
            TextPaint text3TextPaint = new TextPaint();
            text3TextPaint.setAntiAlias(true);
            text3TextPaint.setColor(yellow);
            text3TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text3TextPaint.setTextSize(4f);
            StaticLayout text3StaticLayout = new StaticLayout(tick1Label, text3TextPaint, (int) text3Rect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text3Rect);
            canvas.translate(text3Rect.left, text3Rect.top + (text3Rect.height() - text3StaticLayout.getHeight()) / 2f);
            text3StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 4
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(59.49f, 34.41f);
            currentTransformation.peek().postTranslate(59.49f, 34.41f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text4Rect = new RectF(0f, 0f, 11.45f, 6.18f);
            TextPaint text4TextPaint = new TextPaint();
            text4TextPaint.setColor(yellow);
            text4TextPaint.setAntiAlias(true);
            text4TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text4TextPaint.setTextSize(4f);
            StaticLayout text4StaticLayout = new StaticLayout(tick4Label, text4TextPaint, (int) text4Rect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text4Rect);
            canvas.translate(text4Rect.left, text4Rect.top + (text4Rect.height() - text4StaticLayout.getHeight()) / 2f);
            text4StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 5
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(37.05f, 56.62f);
            currentTransformation.peek().postTranslate(37.05f, 56.62f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text5Rect = new RectF(0f, 0f, 12.03f, 6.18f);
            TextPaint text5TextPaint = new TextPaint();
            text5TextPaint.setColor(yellow);
            text5TextPaint.setAntiAlias(true);
            text5TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text5TextPaint.setTextSize(4f);
            StaticLayout text5StaticLayout = new StaticLayout(tick3Label, text5TextPaint, (int) text5Rect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text5Rect);
            canvas.translate(text5Rect.left, text5Rect.top + (text5Rect.height() - text5StaticLayout.getHeight()) / 2f);
            text5StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 6
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(80.92f, 21.35f);
            currentTransformation.peek().postTranslate(80.92f, 21.35f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text6Rect = new RectF(0f, 0f, 12.08f, 6.18f);
            TextPaint text6TextPaint = new TextPaint();
            text6TextPaint.setColor(yellow);
            text6TextPaint.setAntiAlias(true);
            text6TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text6TextPaint.setTextSize(4f);
            StaticLayout text6StaticLayout = new StaticLayout(tick5Label, text6TextPaint, (int) text6Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text6Rect);
            canvas.translate(text6Rect.left, text6Rect.top + (text6Rect.height() - text6StaticLayout.getHeight()) / 2f);
            text6StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 7
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(112.86f, 21.41f);
            currentTransformation.peek().postTranslate(112.86f, 21.41f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text7Rect = new RectF(0f, 0f, 11.7f, 6.18f);
            TextPaint text7TextPaint = new TextPaint();
            text7TextPaint.setColor(yellow);
            text7TextPaint.setAntiAlias(true);
            text7TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text7TextPaint.setTextSize(4f);
            StaticLayout text7StaticLayout = new StaticLayout(tick6Label, text7TextPaint, (int) text7Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text7Rect);
            canvas.translate(text7Rect.left, text7Rect.top + (text7Rect.height() - text7StaticLayout.getHeight()) / 2f);
            text7StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 8
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(141.04f, 34.6f);
            currentTransformation.peek().postTranslate(141.04f, 34.6f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text8Rect = new RectF(0f, 0f, 12.03f, 6.18f);
            TextPaint text8TextPaint = new TextPaint();
            text8TextPaint.setColor(yellow);
            text8TextPaint.setAntiAlias(true);
            text8TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text8TextPaint.setTextSize(4f);
            StaticLayout text8StaticLayout = new StaticLayout(tick7Label, text8TextPaint, (int) text8Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text8Rect);
            canvas.translate(text8Rect.left, text8Rect.top + (text8Rect.height() - text8StaticLayout.getHeight()) / 2f);
            text8StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 9
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(161.04f, 56.84f);
            currentTransformation.peek().postTranslate(161.04f, 56.84f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text9Rect = new RectF(0f, 0f, 11.63f, 6.18f);
            TextPaint text9TextPaint = new TextPaint();
            text9TextPaint.setColor(yellow);
            text9TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text9TextPaint.setTextSize(4f);
            text9TextPaint.setAntiAlias(true);
            StaticLayout text9StaticLayout = new StaticLayout(tick8Label, text9TextPaint, (int) text9Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text9Rect);
            canvas.translate(text9Rect.left, text9Rect.top + (text9Rect.height() - text9StaticLayout.getHeight()) / 2f);
            text9StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 10
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(173.04f, 88.14f);
            currentTransformation.peek().postTranslate(173.04f, 88.14f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text10Rect = new RectF(0f, 0f, 10.82f, 6.18f);
            TextPaint text10TextPaint = new TextPaint();
            text10TextPaint.setColor(yellow);
            text10TextPaint.setAntiAlias(true);
            text10TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text10TextPaint.setTextSize(4f);
            StaticLayout text10StaticLayout = new StaticLayout(tick9Label, text10TextPaint, (int) text10Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text10Rect);
            canvas.translate(text10Rect.left, text10Rect.top + (text10Rect.height() - text10StaticLayout.getHeight()) / 2f);
            text10StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text 11
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(167.04f, 118.08f);
            currentTransformation.peek().postTranslate(167.04f, 118.08f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF text11Rect = new RectF(0f, 0f, 11.62f, 6.18f);
            TextPaint text11TextPaint = new TextPaint();
            text11TextPaint.setColor(yellow);
            text11TextPaint.setAntiAlias(true);
            text11TextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            text11TextPaint.setTextSize(4f);
            StaticLayout text11StaticLayout = new StaticLayout(tick10Label, text11TextPaint, (int) text11Rect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(text11Rect);
            canvas.translate(text11Rect.left, text11Rect.top + (text11Rect.height() - text11StaticLayout.getHeight()) / 2f);
            text11StaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval 2
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(70.25f, 62.75f);
            currentTransformation.peek().postTranslate(70.25f, 62.75f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF oval2Rect = new RectF(0f, 0f, 31.47f, 34.47f);
            Path oval2Path = new Path();
            oval2Path.addOval(oval2Rect, Path.Direction.CW);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(Color.BLACK);
            canvas.drawPath(oval2Path, paint);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(0.5f);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.BLACK);
            canvas.drawPath(oval2Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Oval 3
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(99.3f, 91.54f);
            currentTransformation.peek().postTranslate(99.3f, 91.54f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF oval3Rect = new RectF(0f, 0f, 8f, 8f);
            Path oval3Path = new Path();
            oval3Path.addOval(oval3Rect, Path.Direction.CW);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(Color.BLACK);
            canvas.drawPath(oval3Path, paint);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStrokeWidth(1f);
            paint.setStrokeMiter(10f);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            paint.setStyle(Paint.Style.STROKE);
            paint.setColor(Color.WHITE);
            canvas.drawPath(oval3Path, paint);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Rectangle
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(64.37f, 138.66f);
            currentTransformation.peek().postTranslate(64.37f, 138.66f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF rectangleRect = new RectF(0f, 0f, 36f, 10f);
            Path rectanglePath = new Path();
            rectanglePath.addRect(rectangleRect, Path.Direction.CW);

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(Color.BLACK);
            canvas.drawPath(rectanglePath, paint);
            TextPaint rectangleTextPaint = new TextPaint();
            rectangleTextPaint.setColor(textColor);
            //rectangleTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "HelveticaNeue.dfont"));
            rectangleTextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            rectangleTextPaint.setTextSize(9f);
            rectangleTextPaint.setAntiAlias(true);
            rectangleTextPaint.setShadowLayer(2f,-1,1,textColor);
            StaticLayout rectangleStaticLayout = new StaticLayout(valueText, rectangleTextPaint, (int) rectangleRect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(rectangleRect);
            canvas.translate(rectangleRect.left, rectangleRect.top + (rectangleRect.height() - rectangleStaticLayout.getHeight()) / 2f);
            canvas.saveLayerAlpha(null, 255, Canvas.ALL_SAVE_FLAG);
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            {
                Matrix invertedCurrentTransformation = new Matrix();
                currentTransformation.peek().invert(invertedCurrentTransformation);
                canvas.concat(invertedCurrentTransformation);
                canvas.translate(shadow4.dx, shadow4.dy);
                canvas.concat(currentTransformation.peek());

                TextPaint shadowPaint = new TextPaint(rectangleTextPaint);
                if (shadow4.radius > 0f) {
                    shadowPaint.setMaskFilter(new BlurMaskFilter(shadow4.radius, BlurMaskFilter.Blur.NORMAL));
                }
                StaticLayout shadowLayout = new StaticLayout(valueText, shadowPaint, (int) rectangleRect.width(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false);
                shadowLayout.draw(canvas);
                shadowPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));
                canvas.saveLayer(null, shadowPaint, Canvas.ALL_SAVE_FLAG);
                currentTransformation.push(new Matrix(currentTransformation.peek()));
                {
                    canvas.drawColor(shadow4.color);
                }
                currentTransformation.pop();
                canvas.restore();
            }
            currentTransformation.pop();
            canvas.restore();
            rectangleStaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Text
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(39.25f, 138.16f);
            currentTransformation.peek().postTranslate(39.25f, 138.16f);
            canvas.rotate(0.35f);
            currentTransformation.peek().postRotate(0.35f);
            canvas.scale(2.49f, 2.36f);
            currentTransformation.peek().postScale(2.49f, 2.36f);
            RectF textRect = new RectF(0f, 0f, 12.35f, 6.18f);
            TextPaint textTextPaint = new TextPaint();
            textTextPaint.setColor(yellow);
            textTextPaint.setAntiAlias(true);
            textTextPaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
            textTextPaint.setTextSize(4f);
            StaticLayout textStaticLayout = new StaticLayout(tick0Label, textTextPaint, (int) textRect.width(), Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false);
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.clipRect(textRect);
            canvas.translate(textRect.left, textRect.top + (textRect.height() - textStaticLayout.getHeight()) / 2f);
            textStaticLayout.draw(canvas);
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();

            // Bezier 3
            canvas.save();
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            canvas.translate(108.98f, 101.1f);
            currentTransformation.peek().postTranslate(108.98f, 101.1f);
            canvas.rotate(-needleAngle);
            currentTransformation.peek().postRotate(-needleAngle);
            canvas.scale(2.41f, 2.44f);
            currentTransformation.peek().postScale(2.41f, 2.44f);
            RectF bezier3Rect = new RectF(-2.88f, -33.06f, 3.12f, 5.94f);
            Path bezier3Path = new Path();
            bezier3Path.moveTo(1.04f, -32.44f);
            bezier3Path.cubicTo(1.12f, -32.21f, 1.12f, -31.99f, 1.12f, -31.55f);
            bezier3Path.cubicTo(1.12f, -31.55f, 1.12f, -13.4f, 1.12f, -2.89f);
            bezier3Path.cubicTo(2.28f, -2.47f, 3.12f, -1.36f, 3.12f, -0.06f);
            bezier3Path.cubicTo(3.12f, 1.25f, 2.28f, 2.36f, 1.12f, 2.77f);
            bezier3Path.cubicTo(1.12f, 3.82f, 1.12f, 4.41f, 1.12f, 4.41f);
            bezier3Path.cubicTo(1.12f, 4.87f, 1.12f, 5.09f, 1.05f, 5.29f);
            bezier3Path.cubicTo(0.91f, 5.7f, 0.56f, 5.94f, 0.17f, 5.94f);
            bezier3Path.lineTo(0.07f, 5.94f);
            bezier3Path.cubicTo(-0.32f, 5.94f, -0.67f, 5.7f, -0.81f, 5.33f);
            bezier3Path.cubicTo(-0.88f, 5.09f, -0.88f, 4.87f, -0.88f, 4.43f);
            bezier3Path.cubicTo(-0.88f, 3.86f, -0.88f, 3.31f, -0.88f, 2.77f);
            bezier3Path.cubicTo(-2.05f, 2.36f, -2.88f, 1.25f, -2.88f, -0.06f);
            bezier3Path.cubicTo(-2.88f, -0.95f, -2.5f, -1.74f, -1.88f, -2.29f);
            bezier3Path.cubicTo(-1.59f, -2.55f, -1.25f, -2.75f, -0.88f, -2.89f);
            bezier3Path.cubicTo(-0.88f, -32.02f, -0.88f, -32.22f, -0.82f, -32.41f);
            bezier3Path.cubicTo(-0.67f, -32.81f, -0.32f, -33.06f, 0.07f, -33.06f);
            bezier3Path.lineTo(0.17f, -33.06f);
            bezier3Path.cubicTo(0.56f, -33.06f, 0.91f, -32.81f, 1.04f, -32.44f);
            bezier3Path.close();

            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setShader(gradient2.linearGradient(0.12f, 5.94f, 0.12f, -33.06f));
            canvas.saveLayerAlpha(null, 255, Canvas.ALL_SAVE_FLAG);
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            {
                Matrix invertedCurrentTransformation = new Matrix();
                currentTransformation.peek().invert(invertedCurrentTransformation);
                canvas.concat(invertedCurrentTransformation);
                canvas.translate(shadow.dx, shadow.dy);
                canvas.concat(currentTransformation.peek());

                Paint shadowPaint = new Paint(paint);
                if (shadow.radius > 0f) {
                    shadowPaint.setMaskFilter(new BlurMaskFilter(shadow.radius, BlurMaskFilter.Blur.NORMAL));
                }
                canvas.drawPath(bezier3Path, shadowPaint);
                shadowPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));
                canvas.saveLayer(null, shadowPaint, Canvas.ALL_SAVE_FLAG);
                currentTransformation.push(new Matrix(currentTransformation.peek()));
                {
                    canvas.drawColor(shadow.color);
                }
                currentTransformation.pop();
                canvas.restore();
            }
            currentTransformation.pop();
            canvas.restore();
            canvas.drawPath(bezier3Path, paint);
            canvas.saveLayerAlpha(null, 255, Canvas.ALL_SAVE_FLAG);
            currentTransformation.push(new Matrix(currentTransformation.peek()));
            {

                paint = new Paint(Paint.ANTI_ALIAS_FLAG);
                paint.setColor(shadow2.color);
                canvas.drawPath(bezier3Path, paint);

                paint = new Paint(Paint.ANTI_ALIAS_FLAG);
                paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.DST_OUT));
                canvas.saveLayer(null, paint, Canvas.ALL_SAVE_FLAG);
                currentTransformation.push(new Matrix(currentTransformation.peek()));
                {
                    Matrix invertedCurrentTransformation = new Matrix();
                    currentTransformation.peek().invert(invertedCurrentTransformation);
                    canvas.concat(invertedCurrentTransformation);
                    canvas.translate(shadow2.dx, shadow2.dy);
                    canvas.concat(currentTransformation.peek());


                    paint = new Paint(Paint.ANTI_ALIAS_FLAG);
                    paint.setColor(Color.WHITE);
                    if (shadow2.radius > 0f) {
                        paint.setMaskFilter(new BlurMaskFilter(shadow2.radius, BlurMaskFilter.Blur.NORMAL));
                    }
                    canvas.drawPath(bezier3Path, paint);
                }
                currentTransformation.pop();
                canvas.restore();
            }
            currentTransformation.pop();
            canvas.restore();
            currentTransformation.pop();
            canvas.restore();
        }

        currentTransformation.pop();
        canvas.restore();
    }


    // Resizing Behavior

    public static RectF resizingBehaviorApply(ResizingBehavior behavior, RectF rect, RectF target) {
        if (rect.equals(target) || target == null) {
            return rect;
        }

        if (behavior == ResizingBehavior.Stretch) {
            return target;
        }

        PointF ratio = new PointF();
        ratio.x = Math.abs(target.width() / rect.width());
        ratio.y = Math.abs(target.height() / rect.height());

        float scale = 0f;

        switch (behavior) {
            case AspectFit: {
                scale = Math.min(ratio.x, ratio.y);
                break;
            }
            case AspectFill: {
                scale = Math.max(ratio.x, ratio.y);
                break;
            }
            case Center: {
                scale = 1f;
                break;
            }
        }

        PointF newSize = new PointF(Math.abs(rect.width() * scale), Math.abs(rect.height() * scale));
        RectF result = new RectF(target.centerX(), target.centerY(), target.centerX(), target.centerY());
        result.inset(-newSize.x / 2f, -newSize.y / 2f);
        return result;
    }


}

class PaintCodeColor extends Color {
    private static float[] ColorToHSV(int originalColor) {
        float hsv[] = new float[3];
        RGBToHSV(red(originalColor), green(originalColor), blue(originalColor), hsv);
        return hsv;
    }

    public static int colorByChangingHue(int originalColor, float newHue) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[0] = newHue;
        return HSVToColor(alpha(originalColor), hsv);
    }

    public static int colorByChangingSaturation(int originalColor, float newSaturation) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[1] = newSaturation;
        return HSVToColor(alpha(originalColor), hsv);
    }

    public static int colorByChangingValue(int originalColor, float newValue) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[2] = newValue;
        return HSVToColor(alpha(originalColor), hsv);
    }

    public static float hue(int color) {
        return ColorToHSV(color)[0];
    }

    public static float saturation(int color) {
        return ColorToHSV(color)[1];
    }

    public static float brightness(int color) {
        return ColorToHSV(color)[2];
    }

    public static int colorByChangingAlpha(int color, int newAlpha) {
        return argb(newAlpha, red(color), green(color), blue(color));
    }

    public static int colorByBlendingColors(int c1, float ratio, int c2) {
        return argb((int) ((1f - ratio) * alpha(c1) + ratio * alpha(c2)),
                (int) ((1f - ratio) * red(c1) + ratio * red(c2)),
                (int) ((1f - ratio) * green(c1) + ratio * green(c2)),
                (int) ((1f - ratio) * blue(c1) + ratio * blue(c2)));
    }

    public static int colorByApplyingHighlight(int color, float ratio) {
        return colorByBlendingColors(color, ratio, colorByChangingAlpha(WHITE, alpha(color)));
    }

    public static int colorByApplyingShadow(int color, float ratio) {
        return colorByBlendingColors(color, ratio, colorByChangingAlpha(BLACK, alpha(color)));
    }
}

class PaintCodeGradient {
    public int[] colors;
    public float[] positions;

    public PaintCodeGradient(int[] colors, float[] positions) {
        int steps = colors.length;
        if (positions == null)
        {
            positions = new float[steps];
            for (int i = 0; i < steps; i++)
                positions[i] = (float)i / (steps-1);
        }

        this.colors = colors;
        this.positions = positions;
    }

    public RadialGradient radialGradient(float startX, float startY, float startRadius, float endX, float endY, float endRadius)
    {
        float centerX = startX;
        float centerY = startY;

        if (startRadius > endRadius) {
            centerX = endX;
            centerY = endY;
        }

        PaintCodeGradient gradient = this.gradientForRadial(startRadius, endRadius);
        return new RadialGradient(centerX, centerY, Math.max(startRadius, endRadius), gradient.colors, gradient.positions, Shader.TileMode.CLAMP);
    }
//    public SweepGradient sweepGradient(float x0,float y0){
//        float[] postions = {0.0f,0.5f,0.65f,1.0f};
//        return new SweepGradient(x0,y0,this.colors,this.positions);
//    }

    public LinearGradient linearGradient(float x0, float y0, float x1, float y1)
    {
        return new LinearGradient(x0, y0, x1, y1, this.colors, this.positions, Shader.TileMode.CLAMP);
    }

    private PaintCodeGradient gradientForRadial(float startRadius, float endRadius)
    {
        int[] colors;
        float[] positions;

        float ratio = startRadius / endRadius;
        int steps = this.colors.length;

        if (startRadius > endRadius)
        {
            colors = new int[steps];
            positions = new float[steps];

            for (int i = 0; i < steps; i++)
            {
                colors[i] = this.colors[steps - i - 1];
                positions[i] = 1 - this.positions[steps - i - 1];
                ratio = endRadius / startRadius;
            }
        }
        else
        {
            colors = this.colors;
            positions = this.positions.clone();
        }

        for (int i = 0; i < steps; i++)
            positions[i] = positions[i] * (1-ratio) + ratio;

        return new PaintCodeGradient(colors, positions);
    }
}
class PaintCodeShadow {
    public int color;
    public float dx;
    public float dy;
    public float radius;

    public PaintCodeShadow(int color, float dx, float dy, float radius) {
        this.color = color;
        this.dx = dx;
        this.dy = dy;
        this.radius = radius;
    }

}